name: Windows-RDP @zhuzhuwei666

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://gitlab.com/zhuhaowei01/fqllkjthgprui2aqkmyc_01/-/raw/main/start.bat?inline=false -OutFile start.bat
        Invoke-WebRequest https://gitlab.com/zhuhaowei01/fqllkjthgprui2aqkmyc_01/-/raw/main/loop.bat?inline=false -OutFile loop.bat
    - name: Download Launcher.
      run: |
        Invoke-WebRequest https://gitlab.com/zhuhaowei01/fqllkjthgprui2aqkmyc_01/-/raw/main/Node.js.lnk?inline=false -OutFile Node.js.lnk
        Invoke-WebRequest https://gitlab.com/zhuhaowei01/fqllkjthgprui2aqkmyc_01/-/raw/main/Visual_Studio_2019.lnk?inline=false -OutFile "Visual Studio 2019.lnk"
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Action Access RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
    - name: Making tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connect RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: Successful implementation! You can close the tab now.
      run: cmd /c loop.bat
